[project]
name = "webgis_ui_prototype"
version = "0.1.0"
description = "webgis_ui_prototype using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.3"
]

[project.scripts]
webgis_ui_prototype = "webgis_ui_prototype.main:run"
run_crew = "webgis_ui_prototype.main:run"
train = "webgis_ui_prototype.main:train"
replay = "webgis_ui_prototype.main:replay"
test = "webgis_ui_prototype.main:test"
run_with_trigger = "webgis_ui_prototype.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
